### ISSUE TITLE
Exception with Vperm

### ISSUE THREAD

**Issue by StachuDotNet** [josef-jelinek/acube#1]
## 9 (to reset)
# Template:

UF UR UB UL DF DR DB DL FR FL BR BL UFR URB UBL ULF DRF DFL DLB DBR
# Current:

UF UR UB UL DF DR DB DL FR FL BR BL UFR URB UBL ULF DRF DFL DLB DBR
## 2: (UF UR) (URB ULF)
# Template:

UF UR UB UL DF DR DB DL FR FL BR BL UFR URB UBL ULF DRF DFL DLB DBR
# Current:

UR UF UB UL DF DR DB DL FR FL BR BL UFR ULF UBL URB DRF DFL DLB DBR
# Turns:

U U2 U' D D2 D' F F2 F' B B2 B' L L2 L' R R2 R' u u2 u' d d2 d' f f2 f' b b2 b'
l l2 l' r r2 r' E E2 E' S S2 S' M M2 M'
## 3: l\* L\* r\* R\* U*
# Template:

UF UR UB UL DF DR DB DL FR FL BR BL UFR URB UBL ULF DRF DFL DLB DBR
# Current:

UR UF UB UL DF DR DB DL FR FL BR BL UFR ULF UBL URB DRF DFL DLB DBR
# Turns:

U U2 U' L L2 L' R R2 R' l l2 l' r r2 r'
## 5: 16
# Template:

UF UR UB UL DF DR DB DL FR FL BR BL UFR URB UBL ULF DRF DFL DLB DBR
# Current:

UR UF UB UL DF DR DB DL FR FL BR BL UFR ULF UBL URB DRF DFL DLB DBR
# Turns:

U U2 U' L L2 L' R R2 R' l l2 l' r r2 r'
## 4: qtm
# Template:

UF UR UB UL DF DR DB DL FR FL BR BL UFR URB UBL ULF DRF DFL DLB DBR
# Current:

UR UF UB UL DF DR DB DL FR FL BR BL UFR ULF UBL URB DRF DFL DLB DBR
# Turns:

U U2 U' L L2 L' R R2 R' l l2 l' r r2 r'

|i| solving UR UF UB UL DF DR DB DL FR FL BR BL UFR ULF UBL URB DRF DFL DLB DBR
|i| creating transformation table (corner orientation)
|i| creating transformation table (edge orientation)
|i| creating transformation table (corner position)
|i| creating transformation table (middle edge position)
|i| creating transformation table (U edge position)
|i| creating transformation table (D edge position)
|i| creating transformation table (middle edge position set)
|i| creating conversion table (middle edge position - middle edge position set)
|i| creating pruning table (corner twist + edge flip)
|i| creating pruning table (corner twist + middle edge position set)
|i| creating pruning table (edge flip + middle edge position set)
|i| creating turn transformation and pruning table
|i| creating transformation table (middle edge position B)
|i| creating transformation table (U/D edge position B)
|i| creating transformation table (corner position B)
|i| creating conversion tables from phase A to phase B
|i| creating pruning table (middle edge position + corner position)
|i| creating pruning table (middle edge position + U/D edge position)
|i| depth 0
|i| depth 1
|i| depth 2
Exception in thread "main" java.lang.NullPointerException
        at acube.transform.MoveTableShort.turn(MoveTableShort.java:21)
        at acube.Solver.searchB(Solver.java:295)
        at acube.Solver.solveB(Solver.java:270)
        at acube.Solver.searchA(Solver.java:229)
        at acube.Solver.solveA(Solver.java:159)
        at acube.Solver.solve(Solver.java:138)
        at acube.CubeState.solve(CubeState.java:63)
        at acube.console.ACube.main(ACube.java:75)

**Comment by josef-jelinek** [comment]
fixed. phase A to phase B used transition that could meet cube rotated to its side making B turns invalid B turns from the cube's point of view...
